#!/usr/bin/env python3
"""Ratchet on hardcoded colours in first-party CSS: the count may fall, never rise.

Background
----------
The product's own stylesheets were written with literal hex, so a site's theme
reached almost none of the interface -- the admin rendered in Foundation's
factory blue no matter what the theme said. Routing those colours to
``var(--sc-*)`` is ongoing and deliberately incremental.

Incremental only works if the number moves one way. Without a ratchet, every new
rule is an opportunity to add another literal, and the routing work is spent
keeping level instead of getting ahead. This fails the build when any tracked
file gains hardcoded colours relative to a committed baseline.

What counts
-----------
A hex literal **outside** a ``var()`` fallback. A routed declaration such as
``color: var(--sc-text, #17191e)`` is not a hardcoded colour -- the literal is
the documented degradation path if the token stylesheet fails to load, and
penalising it would push authors to drop fallbacks, which is worse.

``platform-tokens.css`` is excluded: it is where colours are *supposed* to be
literal. Vendored stylesheets are excluded too -- ``foundation.tokens.min.css``
is generated by tools/route-foundation-tokens.py, which has its own check.

Modes
-----
Default verifies against ``tools/css-colour-baseline.txt`` and exits 1 if any
file is above its baseline. ``--write`` regenerates the baseline; run it after
deliberately routing colours so the ratchet tightens, and commit the result --
which makes every improvement show up in review as a smaller number.

A file that drops below its baseline is reported, not failed, with a nudge to
re-run ``--write``. The check is a floor, not an equality test, so an
in-progress branch is never blocked by a stale baseline.
"""

import argparse
import re
import sys
from pathlib import Path

BASELINE = "tools/css-colour-baseline.txt"
CSS_DIR = "src/main/webapp/css"
EXCLUDE = {"platform-tokens.css"}

VAR_FALLBACK = re.compile(r"var\(\s*--[a-z0-9-]+\s*,\s*[^)]*\)", re.IGNORECASE)
HEX = re.compile(r"#[0-9a-fA-F]{3,8}\b")


def tracked_files(root: Path) -> list[Path]:
    """First-party platform stylesheets only, in a stable order."""
    d = root / CSS_DIR
    if not d.is_dir():
        return []
    return sorted(p for p in d.glob("platform*.css") if p.name not in EXCLUDE)


def hardcoded_count(text: str) -> int:
    """Hex literals outside var() fallbacks."""
    return len(HEX.findall(VAR_FALLBACK.sub("", text)))


def current_counts(root: Path) -> dict[str, int]:
    return {
        str(p.relative_to(root).as_posix()): hardcoded_count(p.read_text(encoding="utf-8"))
        for p in tracked_files(root)
    }


def read_baseline(path: Path) -> dict[str, int]:
    counts = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        count, rel = line.split(None, 1)
        counts[rel] = int(count)
    return counts


def write_baseline(path: Path, counts: dict[str, int]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Hardcoded colour literals per first-party stylesheet (outside var() fallbacks).",
        "# Generated by tools/check-css-token-adoption.py --write. The numbers may fall,",
        "# never rise -- see that script's docstring for why.",
    ]
    lines += [f"{count} {rel}" for rel, count in sorted(counts.items())]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("root", nargs="?", default=".")
    ap.add_argument("--write", action="store_true", help="regenerate the baseline")
    args = ap.parse_args()
    root = Path(args.root)
    baseline_path = root / BASELINE

    counts = current_counts(root)
    if args.write:
        write_baseline(baseline_path, counts)
        print(f"wrote {BASELINE} ({sum(counts.values())} hardcoded colours across {len(counts)} files)")
        return 0

    if not baseline_path.exists():
        print(f"MISSING  {BASELINE} -- run: python3 tools/check-css-token-adoption.py --write",
              file=sys.stderr)
        return 1

    base = read_baseline(baseline_path)
    regressions, improvements, untracked = [], [], []
    for rel, count in counts.items():
        if rel not in base:
            untracked.append(rel)
        elif count > base[rel]:
            regressions.append((rel, base[rel], count))
        elif count < base[rel]:
            improvements.append((rel, base[rel], count))

    for rel, was, now in regressions:
        print(f"REGRESSED  {rel}: {was} -> {now} hardcoded colours", file=sys.stderr)
    for rel in untracked:
        print(f"UNTRACKED  {rel} is not in the baseline -- run --write", file=sys.stderr)
    for rel, was, now in improvements:
        print(f"improved   {rel}: {was} -> {now}  (run --write to tighten the ratchet)")

    if regressions or untracked:
        print("\nRoute new colours to var(--sc-*) instead of adding literals, or run --write\n"
              "if the increase is deliberate and justified in review.", file=sys.stderr)
        return 1

    print(f"OK  {sum(counts.values())} hardcoded colours across {len(counts)} files, none above baseline")
    return 0


if __name__ == "__main__":
    sys.exit(main())
