#!/usr/bin/env python3
"""Report JSP EL expressions that reach the page without escaping.

Background
----------
In a JSP, ``<c:out value="${x}"/>`` escapes HTML but a bare ``${x}`` does not.
A bare expression is only safe when the value cannot carry attacker-controlled
markup -- because it is generated by the framework, is numeric, was sanitized
before storage, or was validated at its source.

That distinction is easy to lose. A wiki page body was stored unsanitized and
rendered through a bare ``${contentHtml}``, which let anyone who could edit a
wiki run script in an administrator's browser. Nothing flagged it, because
rendering sanitized content unescaped is normal and correct everywhere else in
this codebase -- the bug was that this particular value had never been cleaned.

What it does
------------
Finds every EL expression that lands in one of two injection contexts:

  HTML  rendered into the document body, where markup executes
  JS    rendered inside a <script> block, where a quote breaks out of a string

and reports the ones that are not obviously safe. Expressions that are already
escaped (``html:toHtml``, ``js:escape``, ``url:encodeUri``), that are framework
values, or that are numeric are ignored. Everything else must appear in
ALLOWLIST with the reason it is safe.

The point is not to eliminate unescaped output -- much of it is deliberate and
correct. The point is that each one has a recorded justification, and that a
NEW one cannot appear without somebody writing that justification down.

Modes
-----
Report-only by default. ``--strict`` (or ``STRICT=1``) exits 1 on any
unallowlisted finding. CI runs it with ``--strict``: the sweep that produced
this fixed 29 injection points and classified the remainder, so every site that
still renders unescaped carries an entry below explaining why it is safe.

This is a read-only reporter. It changes no files.
"""
from __future__ import annotations

import argparse
import collections
import io
import os
import re
import sys

JSP_ROOT = "src/main/webapp/WEB-INF/jsp"

# Expressions already run through an escaping function.
ESCAPED = re.compile(r"\$\{\s*(html:toHtml|js:escape|url:encode|url:encodeUri|date:|font:|markdown:html|html:clean)\b")

# Framework-generated values that never carry user input.
FRAMEWORK = re.compile(
    r"^\$\{(ctx|i|widgetContext\.\w+|userSession\.formToken"
    r"|systemPropertyMap\['system\.www\.context'\])\}$")

# Numeric or generated-identifier values that cannot express markup.
NUMERIC = re.compile(
    r"^\$\{[\w.\[\]']*?("
    r"[Ii]d|[Cc]ount|[Ss]ize|[Ww]idth|[Hh]eight|[Pp]rice|[Zz]oom|[Ii]ndex|[Tt]otal"
    r"|latitude|longitude|[Pp]rogress|[Dd]ifference|maxValue|pageNumber|pageSize"
    r"|[Dd]elay|[Qq]uantity|[Pp]ercent|[Ll]imit"
    r")\}$"
    r"|^\$\{[\w.]+\s*[-+]\s*\d+\}$"          # ${recordPaging.pageNumber - 1}
    r"|^\$\{[\w.]+\(\)\}$")                   # ${recordList.size()}

# Unescaped output that is DELIBERATE, with the reason it is safe. Keyed by
# "<jsp path>:<expression>" for a specific site, or just "<expression>" to
# cover every occurrence. Add an entry only after tracing the value to its
# source and confirming it is sanitized, validated, or structurally safe.
ALLOWLIST: dict[str, str] = {
    "${mapCredentials.tileServerUrl}":
        "FindMapTilesCredentialsCommand.validatedTileServerUrl rejects quotes, whitespace, backslashes and angle brackets before the value is stored -- validated at the source instead of escaped at the sink",
    "${activity.messageHtml}":
        "Identical path to line 78 — same bean property, same single producer.",
    "${activityDate}":
        "activityDate is machine-generated: ActivityListWidget.java:76-78 sets it to either the literal '---' or FormatDateCommand.formatMonthDayYear(...), which (FormatDateCommand.java:41-",
    "${blogPost.body}":
        "SANITIZED ON SAVE by HtmlCommand.cleanContent at SaveBlogPostCommand.java:73, result assigned via setBody at line 106.",
    "${calloutHtml}":
        "NONE is applied, and none is needed for the paths that exist: the value is a pure widget preference passed straight through (OrderConfirmationWidget.java:104) with no ${} substitut",
    "${card1}":
        "HtmlCommand.cleanContent() on save at SaveContentCommand.java:43 (Content path) / WebPageDesignerToXmlCommand.java:140 (designer path).",
    "${card2}":
        "HtmlCommand.cleanContent() on save at SaveContentCommand.java:43 (Content path) / WebPageDesignerToXmlCommand.java:140 (designer path).",
    "${card}":
        "HtmlCommand.cleanContent() on save at SaveContentCommand.java:43 (Content path) / WebPageDesignerToXmlCommand.java:140 (designer path).",
    "${contentHtml}":
        "Not needed on this path: the string is framework-generated markup, not stored or user-submitted content.",
    "${contentTab.html}":
        "Sanitized before storage.",
    "${content}":
        "Sanitized on render by jsoup, not by HtmlCommand: RemoteContentWidget.java:122-143 builds Safelist.relaxed() (plus span/style), runs Cleaner.clean() and emits clean.body().html(),",
    "${data.value}":
        "Every report that can reach the bar/line chart JSPs populates StatisticsData.value with `String.valueOf(rs.getLong(...))` over a COUNT/aggregate column, so the field holds only dig",
    "${extraHTMLContent}":
        "N/A -- the attribute is never set for this JSP, and cross-widget leakage of the attribute is prevented by an explicit per-widget request-attribute reset.",
    "${file.baseUrl}":
        "None needed - the value contains no user input at all.",
    "${file.url}":
        "Not HtmlCommand.",
    "${fn:substringAfter(recordPagingParams, '&')}":
        "fn:substringAfter only strips the leading '&', and every producer of an '&'-prefixed recordPagingParams builds it from a numeric Category.id (Long, Category.java:31) plus url:encod",
    "${footerHtml}":
        "NONE is applied, and none is required for the paths that exist.",
    "${hideChartControls}":
        "SupersetWidget.java:56-59 sets this from a Java boolean via a ternary, so it is one of the two literals true/false and the operator's preference text is discarded after a 'true'.equals() comparison",
    "${hideChartTitle}":
        "Both attributes are set from a Java boolean via the ternary `hideChartTitle ? 'true' : 'false'` (and likewise for hideChartControls), so the request attribute is one of exactly two",
    "${html}":
        "SAFE — the value is HTML by design and is run through HtmlCommand.cleanContent (jsoup Safelist.relaxed, which strips script/style tags and all on* handler attributes) before being",
    "${initialView}":
        "initialView is never a request attribute from Java;",
    "${introHtml}":
        "NONE is applied, and none is required for the paths that exist.",
    "${item.course.enrollments}":
        "`item` is a CourseUserAggregate whose `getCourse()` (domain/model/elearning/CourseUserAggregate.java:40) returns a Course, and Course.enrollments is a Java primitive `int` (domain/",
    "${link['link']}":
        "sanitized by UrlCommand.sanitizeUrl at MenuWidget.java:179, matching what LinkWidget already did",
    "${link}":
        "Sanitized by UrlCommand.sanitizeUrl at LinkWidget.java:64, immediately before the setAttribute at line 68, with an explicit comment: 'The link is rendered into an href attribute;",
    "${mapZoomLevel}":
        "The request attribute is never the raw preference: each owning widget runs the preference through Integer.parseInt and re-serializes the resulting int with String.valueOf, so the r",
    "${minTimestamp}":
        "minTimestamp is a numeric Long, not a string: ActivityListWidget.java:68-69 sets it to System.currentTimeMillis() + 1, so its toString() is only decimal digits and it cannot emit a",
    "${moodleBackgroundColor}":
        "Both are widget preferences, but CalendarWidget.java:84-89 only copies them into the request when ColorCommand.isHexColor() passes, and that check (ColorCommand.java:33-34) require",
    "${moodleTextColor}":
        "CalendarWidget.java:84-89 only copies this preference through when ColorCommand.isHexColor passes, which requires '#' plus exactly six alphanumerics -- excluding the quote, backslash and angle bracket",
    "${optionOrder}":
        "optionOrder is set in the same <c:choose> as initialView to one of three JSP string literals — 'listWeek,dayGridMonth', 'timeGrid,dayGridMonth', or 'dayGridMonth,listWeek' (full-ca",
    "${order.totalItems}":
        "Order.totalItems is a Java primitive `int` (domain/model/ecommerce/Order.java:55, getter `public int getTotalItems()` at Order.java:267), populated only from a computed item count",
    "${pageIndicator}":
        "pageIndicator is a two-value fixed set assigned in the same file immediately above its use — <c:set value='alert'> at layout-header-renderer.jspf:30 and <c:set value='warning'> at",
    "${pageRenderInfo.pagePath}":
        "No application-level escaping or filtering on this path.",
    "${pageValue}":
        "pageValue is the loop variable over recordPaging.pageList, and DataConstraints.getPageList() (DataConstraints.java:176-202) only ever adds String.valueOf-style decimal renderings o",
    "${pricingRule.buyXItems}":
        "PricingRule.buyXItems is a Java primitive `int` (domain/model/ecommerce/PricingRule.java:57, getter `public int getBuyXItems()` at PricingRule.java:257) loaded via `DB.getInt(rs, .",
    "${pricingRule.getYItemsFree}":
        "The EL property resolves to `public int getGetYItemsFree()` (domain/model/ecommerce/PricingRule.java:261) backed by the primitive field `private int getYItemsFree` (PricingRule.jav",
    "${product.description}":
        "SANITIZED ON SAVE by HtmlCommand.cleanContent at SaveProductCommand.java:65, assigned via setDescription at line 83.",
    "${recordPaging.totalRecordCount - activityList.size()}":
        "This is EL arithmetic, not a string: totalRecordCount is a long field (DataConstraints.java:35, setter at :88) and List.size() is an int, so the subtraction yields a numeric result",
    "${recordPagingParams}":
        "Per producer: (1) src/main/java/com/simisinc/platform/presentation/widgets/admin/audit/AuditLogListWidget.java:112-120 builds the string via appendParam(), which applies `URLEncode",
    "${returnPage}":
        "UrlCommand.getValidReturnPage() at src/main/java/com/simisinc/platform/application/cms/UrlCommand.java:86-98, backed by the allow-list regex SAFE_RETURN_PAGE at UrlCommand.java:84:",
    "${searchResult.htmlExcerpt}":
        "HtmlCommand.toHtml() == org.apache.commons.text.StringEscapeUtils.escapeHtml4() applied at BlogPostSearchResultsWidget.java:88, immediately before the value is stored on the bean.",
    "${section.labelsList[cardStatus.index]}":
        "the label is sliced from the accordion html preference, which ContentHtmlCommand now runs through HtmlCommand.cleanContent before any widget sees it",
    "${siteProperty.name}":
        "None applied, and none needed: the string is never attacker-influenced.",
    "${subFolder.posterFileItem.url}":
        "Not HtmlCommand.",
    "${thisDay}":
        "thisDay is produced one line earlier by <fmt:formatDate pattern='MMMM d, yyyy' value='${calendarEvent.startDate}'> (calendar-search-results.jsp:47 and upcoming-events.jsp:47) appli",
    "${titleHtml}":
        "NONE is applied, and none is required for the paths that exist.",
    "${tokenResult.status}":
        "This is a JavaScript template-literal placeholder inside a backtick string, not a JSP value: `tokenResult` is a local JS const declared at customer-payment-form-square.jsp:52 and t",
    "${userSession.user.email}":
        "NONE — no HtmlCommand.cleanContent, no cleanRenderedMarkdown, no <c:out>.",
    "${widget.content}":
        "None applied at this point, and none is possible or correct: the value is not a data field, it is the already-rendered HTML document fragment produced by a widget.",
    "${year.key}":
        "None needed - the value is a java.lang.Long produced by the database, not a string that ever held user input.",
    "${year}":
        "SAFE — ${year} is a java.lang.Long element of folderYearList, populated at src/main/java/com/simisinc/platform/presentation/widgets/cms/FileListByFolderWidget.java:104 from the SQL",
}

CONTEXT_HTML = "HTML"
CONTEXT_JS = "JS"

TAG = re.compile(r"<[^>]*>", re.S)
COMMENT = re.compile(r"<%--.*?--%>", re.S)
SCRIPT = re.compile(r"<script\b[^>]*>(.*?)</script>", re.S | re.I)
EL = re.compile(r"\$\{[^}]+\}")
# A backtick-delimited JS template literal, including newlines.
TEMPLATE_LITERAL = re.compile(r"`[^`]*`", re.S)


def _blank(match) -> str:
    """Replace a span with spaces so byte offsets, and thus line numbers, survive."""
    return " " * len(match.group(0))


def scan(path: str) -> list[tuple[int, str, str]]:
    """Return (line, expression, context) for EL reaching HTML or JS output."""
    src = io.open(path, encoding="utf-8", errors="replace").read()
    found: list[tuple[int, str, str]] = []

    # JS context first, so those offsets can then be removed from the HTML pass.
    js_spans = []
    for m in SCRIPT.finditer(src):
        body = m.group(1)
        # Blank out JSTL tags inside the script: <c:if test="${...}"> is a tag
        # attribute, not JavaScript, and counting it produces pure noise.
        masked = TAG.sub(_blank, COMMENT.sub(_blank, body))
        # Blank out JavaScript template literals. Inside backticks, ${...} is browser-side
        # interpolation evaluated by the JS engine -- the JSP never renders it, so reporting it
        # is a false positive. Doing this after tag masking so a backtick inside an attribute
        # cannot swallow real markup.
        masked = TEMPLATE_LITERAL.sub(_blank, masked)
        for e in EL.finditer(masked):
            line = src.count("\n", 0, m.start(1) + e.start()) + 1
            found.append((line, e.group(0), CONTEXT_JS))
        js_spans.append((m.start(), m.end()))

    # HTML text position: blank every tag and every script block, and whatever
    # EL remains is being written straight into the document body.
    masked = COMMENT.sub(_blank, src)
    masked = SCRIPT.sub(_blank, masked)
    masked = TAG.sub(_blank, masked)
    for e in EL.finditer(masked):
        line = src.count("\n", 0, e.start()) + 1
        found.append((line, e.group(0), CONTEXT_HTML))

    return found


def is_safe(expr: str) -> bool:
    return bool(ESCAPED.match(expr) or FRAMEWORK.match(expr) or NUMERIC.match(expr))


def allow_reason(rel: str, expr: str) -> str | None:
    return ALLOWLIST.get("%s:%s" % (rel, expr)) or ALLOWLIST.get(expr)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("root", nargs="?", default=".")
    ap.add_argument("--strict", action="store_true",
                    default=os.environ.get("STRICT") == "1")
    args = ap.parse_args()

    base = os.path.join(args.root, JSP_ROOT)
    if not os.path.isdir(base):
        sys.exit("error: %s not found (run from the repository root)" % base)

    findings: list[tuple[str, int, str, str]] = []
    allowed: collections.Counter = collections.Counter()
    scanned = 0
    for dirpath, _, files in os.walk(base):
        for name in sorted(files):
            if not (name.endswith(".jsp") or name.endswith(".jspf")):
                continue
            scanned += 1
            path = os.path.join(dirpath, name)
            rel = os.path.relpath(path, base)
            for line, expr, context in scan(path):
                if is_safe(expr):
                    continue
                reason = allow_reason(rel, expr)
                if reason:
                    allowed[expr] += 1
                else:
                    findings.append((rel, line, expr, context))

    print("Unescaped JSP EL report  (%d files under %s)" % (scanned, JSP_ROOT))
    print("=" * 72)
    print()

    if findings:
        by_context = collections.defaultdict(list)
        for rel, line, expr, context in findings:
            by_context[context].append((rel, line, expr))
        for context in (CONTEXT_HTML, CONTEXT_JS):
            rows = by_context.get(context)
            if not rows:
                continue
            label = ("rendered into the document body -- markup executes"
                     if context == CONTEXT_HTML
                     else "rendered inside <script> -- a quote breaks out of the string")
            print("%s CONTEXT (%d) -- %s:" % (context, len(rows), label))
            for rel, line, expr in sorted(rows):
                print("  %-52s %-46s :%d" % (rel, expr, line))
            print()
    else:
        print("No unallowlisted unescaped EL found.")
        print()

    if allowed:
        print("ALLOWLISTED -- deliberate, with a recorded reason (%d expressions, %d sites):"
              % (len(allowed), sum(allowed.values())))
        for expr, count in sorted(allowed.items()):
            print("  %-46s %2d  %s" % (expr, count, ALLOWLIST.get(expr, "(per-site entry)")))
        print()

    print("Summary: %d unallowlisted, %d allowlisted sites." % (len(findings), sum(allowed.values())))

    if findings and args.strict:
        print()
        print("FAIL: unescaped EL without a recorded justification.")
        print("Either wrap the value (<c:out>, js:escape, url:encodeUri), sanitize it at")
        print("the point it is stored, or add an ALLOWLIST entry in this script saying")
        print("why the value cannot carry markup.")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
