#!/usr/bin/env python3
"""Report JSP EL expressions that reach the page without escaping.

Background
----------
In a JSP, ``<c:out value="${x}"/>`` escapes HTML but a bare ``${x}`` does not.
A bare expression is only safe when the value cannot carry attacker-controlled
markup -- because it is generated by the framework, is numeric, was sanitized
before storage, or was validated at its source.

That distinction is easy to lose. A wiki page body was stored unsanitized and
rendered through a bare ``${contentHtml}``, which let anyone who could edit a
wiki run script in an administrator's browser. Nothing flagged it, because
rendering sanitized content unescaped is normal and correct everywhere else in
this codebase -- the bug was that this particular value had never been cleaned.

What it does
------------
Finds every EL expression that lands in one of two injection contexts:

  HTML  rendered into the document body, where markup executes
  JS    rendered inside a <script> block, where a quote breaks out of a string

and reports the ones that are not obviously safe. Expressions that are already
escaped (``html:toHtml``, ``js:escape``, ``url:encodeUri``), that are framework
values, or that are numeric are ignored. Everything else must appear in
ALLOWLIST with the reason it is safe.

The point is not to eliminate unescaped output -- much of it is deliberate and
correct. The point is that each one has a recorded justification, and that a
NEW one cannot appear without somebody writing that justification down.

Modes
-----
Report-only by default. ``--strict`` (or ``STRICT=1``) exits 1 on any
unallowlisted finding.

This is a read-only reporter. It changes no files.
"""
from __future__ import annotations

import argparse
import collections
import io
import os
import re
import sys

JSP_ROOT = "src/main/webapp/WEB-INF/jsp"

# Expressions already run through an escaping function.
ESCAPED = re.compile(r"\$\{\s*(html:toHtml|js:escape|url:encode|url:encodeUri|date:|font:|markdown:html|html:clean)\b")

# Framework-generated values that never carry user input.
FRAMEWORK = re.compile(
    r"^\$\{(ctx|i|widgetContext\.\w+|userSession\.formToken"
    r"|systemPropertyMap\['system\.www\.context'\])\}$")

# Numeric or generated-identifier values that cannot express markup.
NUMERIC = re.compile(
    r"^\$\{[\w.\[\]']*?("
    r"[Ii]d|[Cc]ount|[Ss]ize|[Ww]idth|[Hh]eight|[Pp]rice|[Zz]oom|[Ii]ndex|[Tt]otal"
    r"|latitude|longitude|[Pp]rogress|[Dd]ifference|maxValue|pageNumber|pageSize"
    r"|[Dd]elay|[Qq]uantity|[Pp]ercent|[Ll]imit"
    r")\}$"
    r"|^\$\{[\w.]+\s*[-+]\s*\d+\}$"          # ${recordPaging.pageNumber - 1}
    r"|^\$\{[\w.]+\(\)\}$")                   # ${recordList.size()}

# Unescaped output that is DELIBERATE, with the reason it is safe. Keyed by
# "<jsp path>:<expression>" for a specific site, or just "<expression>" to
# cover every occurrence. Add an entry only after tracing the value to its
# source and confirming it is sanitized, validated, or structurally safe.
ALLOWLIST: dict[str, str] = {
    # --- validated at the source instead of escaped at the sink ---
    "${mapCredentials.tileServerUrl}":
        "FindMapTilesCredentialsCommand.validatedTileServerUrl rejects quotes, whitespace, "
        "backslashes and angle brackets before the value is ever stored",
}

CONTEXT_HTML = "HTML"
CONTEXT_JS = "JS"

TAG = re.compile(r"<[^>]*>", re.S)
COMMENT = re.compile(r"<%--.*?--%>", re.S)
SCRIPT = re.compile(r"<script\b[^>]*>(.*?)</script>", re.S | re.I)
EL = re.compile(r"\$\{[^}]+\}")


def _blank(match) -> str:
    """Replace a span with spaces so byte offsets, and thus line numbers, survive."""
    return " " * len(match.group(0))


def scan(path: str) -> list[tuple[int, str, str]]:
    """Return (line, expression, context) for EL reaching HTML or JS output."""
    src = io.open(path, encoding="utf-8", errors="replace").read()
    found: list[tuple[int, str, str]] = []

    # JS context first, so those offsets can then be removed from the HTML pass.
    js_spans = []
    for m in SCRIPT.finditer(src):
        body = m.group(1)
        # Blank out JSTL tags inside the script: <c:if test="${...}"> is a tag
        # attribute, not JavaScript, and counting it produces pure noise.
        masked = TAG.sub(_blank, COMMENT.sub(_blank, body))
        for e in EL.finditer(masked):
            line = src.count("\n", 0, m.start(1) + e.start()) + 1
            found.append((line, e.group(0), CONTEXT_JS))
        js_spans.append((m.start(), m.end()))

    # HTML text position: blank every tag and every script block, and whatever
    # EL remains is being written straight into the document body.
    masked = COMMENT.sub(_blank, src)
    masked = SCRIPT.sub(_blank, masked)
    masked = TAG.sub(_blank, masked)
    for e in EL.finditer(masked):
        line = src.count("\n", 0, e.start()) + 1
        found.append((line, e.group(0), CONTEXT_HTML))

    return found


def is_safe(expr: str) -> bool:
    return bool(ESCAPED.match(expr) or FRAMEWORK.match(expr) or NUMERIC.match(expr))


def allow_reason(rel: str, expr: str) -> str | None:
    return ALLOWLIST.get("%s:%s" % (rel, expr)) or ALLOWLIST.get(expr)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("root", nargs="?", default=".")
    ap.add_argument("--strict", action="store_true",
                    default=os.environ.get("STRICT") == "1")
    args = ap.parse_args()

    base = os.path.join(args.root, JSP_ROOT)
    if not os.path.isdir(base):
        sys.exit("error: %s not found (run from the repository root)" % base)

    findings: list[tuple[str, int, str, str]] = []
    allowed: collections.Counter = collections.Counter()
    scanned = 0
    for dirpath, _, files in os.walk(base):
        for name in sorted(files):
            if not (name.endswith(".jsp") or name.endswith(".jspf")):
                continue
            scanned += 1
            path = os.path.join(dirpath, name)
            rel = os.path.relpath(path, base)
            for line, expr, context in scan(path):
                if is_safe(expr):
                    continue
                reason = allow_reason(rel, expr)
                if reason:
                    allowed[expr] += 1
                else:
                    findings.append((rel, line, expr, context))

    print("Unescaped JSP EL report  (%d files under %s)" % (scanned, JSP_ROOT))
    print("=" * 72)
    print()

    if findings:
        by_context = collections.defaultdict(list)
        for rel, line, expr, context in findings:
            by_context[context].append((rel, line, expr))
        for context in (CONTEXT_HTML, CONTEXT_JS):
            rows = by_context.get(context)
            if not rows:
                continue
            label = ("rendered into the document body -- markup executes"
                     if context == CONTEXT_HTML
                     else "rendered inside <script> -- a quote breaks out of the string")
            print("%s CONTEXT (%d) -- %s:" % (context, len(rows), label))
            for rel, line, expr in sorted(rows):
                print("  %-52s %-46s :%d" % (rel, expr, line))
            print()
    else:
        print("No unallowlisted unescaped EL found.")
        print()

    if allowed:
        print("ALLOWLISTED -- deliberate, with a recorded reason (%d expressions, %d sites):"
              % (len(allowed), sum(allowed.values())))
        for expr, count in sorted(allowed.items()):
            print("  %-46s %2d  %s" % (expr, count, ALLOWLIST.get(expr, "(per-site entry)")))
        print()

    print("Summary: %d unallowlisted, %d allowlisted sites." % (len(findings), sum(allowed.values())))

    if findings and args.strict:
        print()
        print("FAIL: unescaped EL without a recorded justification.")
        print("Either wrap the value (<c:out>, js:escape, url:encodeUri), sanitize it at")
        print("the point it is stored, or add an ALLOWLIST entry in this script saying")
        print("why the value cannot carry markup.")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
